### PR TITLE
Update WFS point source driving functions

### PR DESCRIPTION
**Pull request by hagenw**
I have started with the correction of the WFS driving functions in the theory.

This covers the driving functions for a point source.
The old version can be watched online here:
http://sfstoolbox.org/en/nfchoa_line_sources/#sec-driving-functions-wfs-point-source
And the new version including my changes here:
http://sfstoolbox.org/en/update_wfs_ps/#sec-driving-functions-wfs-point-source

Could you please have a look if now everything is fine.

I have cited already the dissertation of Frank, but I'm not sure if this is the official version and the equation numbers will be correct in the end.

### CODE REVIEW

**Comment by fs446** [comment]
Cool!!

You may cite my thesis as of 2016, since it will be released within the 
next days, will share this via DropBox as well.

@PhdThesis{Schultz2016,
   Title                    = {Sound Field Synthesis for Line Source 
Array Applications in Large-Scale Sound Reinforcement},
   Author                   = {Frank Schultz},
   School                   = {University of Rostock},
   Year                     = {2016}
}

I did not change anything crucial within the driving functions under 
discussion, however there might be a different numbering. So I will 
check this once the final version is ready.

However, it might be worth to wait for the final version of the article 
currently under review:

Firtha, G.; Fiala, P.; Schultz, F. & Spors, S. Referencing Schemes for 
Wave Field Synthesis Driving Functions---A Unified Theory IEEE/ACM 
Trans. Audio Speech Language Process., 2016

...since this includes an even more consistent and unified framework as 
the one in Ch 2 of my thesis. It basically allows for arbitrary 
reference curves in front of arbitrary SSDs and the traditional and 
revisited WFS theories are treated as special cases.

Best
Frank

**Comment by hagenw** [comment]
Cool, finally some literature on the strange reference schemes :)

**Comment by hagenw** [comment]
Thanks @fs446.

@fietew: as the documentation is now in line with your implementation in sfstoolbox/sfs#37 I guess I can merge the documentation?

**Comment by fietew** [comment]
Looks good to me

**Pull request merged**
